title: Han Cheng
url: "https://chenghansdu.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/chenghansdu"
footer_text: "© 2026 Han Cheng"

sass:
    style: compressed
    sass_dir: _sass

i18n:
  en:
    title: "Han Cheng"
    home: "/"
    switch_label: "中文"
    switch_lang: "zh-CN"
    footer_text: "© 2026 Han Cheng"

    nav:
      - name: "Resume"
        link: "/resume.pdf"
        new_tab: true

      - name: "Contact"
        link: "/contact"

  zh-CN:
    title: "程涵"
    home: "/zh.html"
    switch_label: "English"
    switch_lang: "en"
    footer_text: "© 2026 Han Cheng"

    nav:
      - name: "简历"
        link: "/resume.pdf"
        new_tab: true

      - name: "联系"
        link: "/contact_zh"
